### ISSUE TITLE
Need links for Messages Podcast (Audio & Video)

### ISSUE THREAD

**Issue by tylerbodway** [tylerbodway/crossroadschurch.net#1]

**Comment by devanflaherty** [comment]
Email sent to Brian Engle for links.
Waiting for response.

**Comment by devanflaherty** [comment]
Have you looked on Haivision yet to see how to get these urls returned to you?

**Comment by tylerbodway** [comment]
Fixed by 9fcb49b365097e5d80d2c27640ba48a578d2dc7a
