### ISSUE TITLE
Series on home page

### ISSUE THREAD

**Issue by devanflaherty** [tylerbodway/crossroadschurch.net#7]
I added a 'custom-field' to the 'Series' Post-Type for featured.
It seems they want only 'featured' series to show on the home-page.

**Two things to keep note of:**

1. That commit I just made to DEV I realized didn't filter the posts by that 'Featured' custom field I created. As well, I didn't have it limit it to only two. Soon. My bad.
2. I wonder if it would be better that rather than them set a series to featured. That we made a 'Feature Series' select box for the home page. Which you can do via 'Custom Fields'. You can have it filter through custom post types, and you can select the post you want. So that might be easier.

Anyways. Let me know what you think.

**Comment by tylerbodway** [comment]
Yeah that seems like a cleaner approach to use custom fields for a select field of series post types on the home page. Development principles would lean towards that approach more I feel.

**Comment by devanflaherty** [comment]
My latest pushes to DEV should make this all happy and good to go.
